apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain =
    [smtp]
    enabled = true
    host: EMAIL_SECURITY_COMPONENT_HOST_PORT
    user: EMAIL_SECURITY_COMPONENT_USER
    password: EMAIL_SECURITY_COMPONENT_PASSWORD
    from_address: EMAIL_SECURITY_COMPONENT
    skip_verify = true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring-system
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.1.4
    helm.sh/chart: grafana-6.38.0
  name: monitoring-grafana
  namespace: monitoring-system
