apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Security-Loki
      type: loki
      url: http://loki-stack:3100
      uid: 3100
      access: proxy
      isDefault: false
      
