{
 "title": "Security Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Attackers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (attacker) (count_over_time({job=\"ingress-controller/ingress-nginx\"} |= \"transaction\" |= \"severity\" |= \"match\" |= \"ruleId\" | json attacker=\"transaction.client_ip\", time=\"transaction.time_stamp\", Server=\"transaction.request.headers.Host\", server=\"transaction.request.headers.host\", tags=\"transaction.messages[0][\\\"details\\\"][\\\"tags\\\"]\", severity=\"transaction.messages[0][\\\"details\\\"][\\\"severity\\\"]\", file=\"transaction.messages[0][\\\"details\\\"][\\\"file\\\"]\", uri=\"transaction.request.uri\", body=\"transaction.request.body\", method=\"transaction.request.method\", headers=\"transaction.request.headers\", ruleid=\"transaction.messages[0][\\\"details\\\"][\\\"ruleId\\\"]\", debug_ruleid=\"transaction.messages[1][\\\"details\\\"][\\\"ruleId\\\"]\", message=\"transaction.messages[0].message\", debug_message=\"transaction.messages[1].message\", status_code=\"transaction.response.http_code\" | ruleid != \"\" | status_code = \"403\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "Activity Per Attacker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (attacker) (count_over_time({job=\"ingress-controller/ingress-nginx\"} |= \"transaction\" |= \"severity\" |= \"match\" |= \"ruleId\" | json attacker=\"transaction.client_ip\", time=\"transaction.time_stamp\", Server=\"transaction.request.headers.Host\", server=\"transaction.request.headers.host\", tags=\"transaction.messages[0][\\\"details\\\"][\\\"tags\\\"]\", severity=\"transaction.messages[0][\\\"details\\\"][\\\"severity\\\"]\", file=\"transaction.messages[0][\\\"details\\\"][\\\"file\\\"]\", uri=\"transaction.request.uri\", body=\"transaction.request.body\", method=\"transaction.request.method\", headers=\"transaction.request.headers\", ruleid=\"transaction.messages[0][\\\"details\\\"][\\\"ruleId\\\"]\", debug_ruleid=\"transaction.messages[1][\\\"details\\\"][\\\"ruleId\\\"]\", message=\"transaction.messages[0].message\", debug_message=\"transaction.messages[1].message\", status_code=\"transaction.response.http_code\" | ruleid != \"\" | status_code = \"403\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{attacker}}"
    }
   ]
  },
  {
   "title": "RuleIDs",
   "type": "stat",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (message, ruleid) (count_over_time({job=\"ingress-controller/ingress-nginx\"} |= \"transaction\" |= \"severity\" |= \"match\" |= \"ruleId\" | json attacker=\"transaction.client_ip\", time=\"transaction.time_stamp\", Server=\"transaction.request.headers.Host\", server=\"transaction.request.headers.host\", tags=\"transaction.messages[0][\\\"details\\\"][\\\"tags\\\"]\", severity=\"transaction.messages[0][\\\"details\\\"][\\\"severity\\\"]\", file=\"transaction.messages[0][\\\"details\\\"][\\\"file\\\"]\", uri=\"transaction.request.uri\", body=\"transaction.request.body\", method=\"transaction.request.method\", headers=\"transaction.request.headers\", ruleid=\"transaction.messages[0][\\\"details\\\"][\\\"ruleId\\\"]\", debug_ruleid=\"transaction.messages[1][\\\"details\\\"][\\\"ruleId\\\"]\", message=\"transaction.messages[0].message\", debug_message=\"transaction.messages[1].message\", status_code=\"transaction.response.http_code\" | ruleid != \"\" | status_code = \"403\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ruleid}} {{message}}"
    }
   ]
  },
  {
   "title": "ModSec Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"ingress-controller/ingress-nginx\"} |= \"transaction\" |= \"severity\" |= \"match\" |= \"ruleId\" | json attacker=\"transaction.client_ip\", time=\"transaction.time_stamp\", Server=\"transaction.request.headers.Host\", server=\"transaction.request.headers.host\", tags=\"transaction.messages[0][\\\"details\\\"][\\\"tags\\\"]\", severity=\"transaction.messages[0][\\\"details\\\"][\\\"severity\\\"]\", file=\"transaction.messages[0][\\\"details\\\"][\\\"file\\\"]\", uri=\"transaction.request.uri\", body=\"transaction.request.body\", method=\"transaction.request.method\", headers=\"transaction.request.headers\", ruleid=\"transaction.messages[0][\\\"details\\\"][\\\"ruleId\\\"]\", debug_ruleid=\"transaction.messages[1][\\\"details\\\"][\\\"ruleId\\\"]\", message=\"transaction.messages[0].message\", debug_message=\"transaction.messages[1].message\", status_code=\"transaction.response.http_code\" | ruleid != \"\" | status_code = \"403\" | __error__=\"\"\n\n| line_format \"➡️ RuleId: {{.ruleid}} {{.message}}\\n🌐 {{.server}}{{.Server}} {{.method}} {{.uri}}\\n️☠️ Client: {{.attacker}}️\\n🏷️ [tag {{.tags}}]\\n🧰 ➡️ RuleId: {{.debug_ruleid}} {{.debug_message}}\""
    }
   ]
  }
 ]
}